pub mod agents;
// Temporarily disabled for compilation
// pub mod model_knowledge_base;
// pub mod execution_service;
// pub mod claude_execution_service;
// pub mod gemini_execution_service;
// pub mod ollama_execution_service;
pub mod ai_benchmark_system;
pub mod ai_usage_tracker;
pub mod ai_session_integrator;
// pub mod auto_model_selection;
pub mod claude;
pub mod claude_sync;
pub mod dashboard;
pub mod dashboard_seed;
pub mod dashboard_utils;
pub mod gemini;
pub mod gemini_enhanced;
pub mod gemini_models;
pub mod gemini_chat;
pub mod gemini_processor;
pub mod gemini_performance;
pub mod gemini_resilience;
pub mod gemini_monitoring;
pub mod gemini_backend;
pub mod gemini_model_manager;
pub mod gemini_request_validator;
pub mod gemini_config_manager;
pub mod gemini_observability;
pub mod gemini_universal;
pub mod gemini_test_suite;
// Temporarily disabled for compilation
// pub mod health_analyzer;
// pub mod ai_analyzer;
// pub mod risk_detector;
// pub mod performance_monitor;
// pub mod documentation_analyzer;
// pub mod workflow_visualizer;
// pub mod realtime_collector;
pub mod mcp;
pub mod usage;
pub mod storage;
pub mod session_manager;
pub mod slash_commands;
pub mod proxy;
pub mod intelligent_routing;
pub mod mcp_manager;
pub mod image_handler;
pub mod ollama;
pub mod session_deduplication;
pub mod universal_tool_executor;
// pub mod universal_model_executor; // Temporarily disabled due to conflicts
pub mod simple_model_validator;
pub mod error_tracker;
pub mod debug_system;
pub mod universal_mcp;
pub mod execution_control;
pub mod app_info;
pub mod version;
pub mod model_health_manager;
pub mod comprehensive_model_validator;
pub mod cross_model_memory;
pub mod context_transfer;
pub mod error_detection_system;
pub mod model_disability_manager;
pub mod intelligence_bridge;
pub mod context_injector;
pub mod rollback;
pub mod ollama_model_detector;
